# Generated by Django 2.2.12 on 2020-05-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0006_delete_language_model'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkgrouplink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menusnippetlink',
            options={},
        ),
        migrations.AddField(
            model_name='linkgrouplink',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkgrouplink',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='linkgrouplink',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='linkgroupsnippet',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkgroupsnippet',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='linkgroupsnippet',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='menusnippet',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menusnippet',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='menusnippet',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='menusnippetlink',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menusnippetlink',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='menusnippetlink',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
