# Generated by Django 2.2.12 on 2020-05-08 10:13

from django.db import migrations

from wagtail_localize.bootstrap import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_localize_1'),
    ]

    operations = [
        BootstrapTranslatableModel('core.HomePage'),
    ]
