# Generated by Django 2.2.12 on 2020-05-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0006_delete_language_model'),
        ('features', '0008_auto_20180604_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bullet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='featurepagefeatureaspect',
            options={},
        ),
        migrations.AddField(
            model_name='bullet',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bullet',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='bullet',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='featureaspect',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureaspect',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='featureaspect',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='featuredescription',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredescription',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='featuredescription',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='featureindexpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureindexpage',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='featureindexpage',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='featureindexpagemenuoption',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureindexpagemenuoption',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='featureindexpagemenuoption',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='featurepagefeatureaspect',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featurepagefeatureaspect',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='featurepagefeatureaspect',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
