# Generated by Django 2.2.12 on 2020-05-08 10:14

from django.db import migrations

from wagtail_localize.bootstrap import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_localize_1'),
    ]

    operations = [
        BootstrapTranslatableModel('features.Bullet'),
        BootstrapTranslatableModel('features.FeatureAspect'),
        BootstrapTranslatableModel('features.FeatureDescription'),
        BootstrapTranslatableModel('features.FeatureIndexPage'),
        BootstrapTranslatableModel('features.FeatureIndexPageMenuOption'),
        BootstrapTranslatableModel('features.FeaturePageFeatureAspect'),
    ]
