# Generated by Django 2.2.12 on 2020-05-08 10:13

from django.db import migrations

from wagtail_localize.bootstrap import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_localize_1'),
    ]

    operations = [
        BootstrapTranslatableModel('blog.Author'),
        BootstrapTranslatableModel('blog.BlogIndexPage'),
        BootstrapTranslatableModel('blog.BlogPage'),
    ]
